### ISSUE TITLE
error when running demo.m

### ISSUE THREAD

**Issue by razoralm** [georgeoneill/EBBcorr#1]
I could not make a pass through the demo.m file without errors.

I add add spm12 to the marlab path (addpath)
Then i run demo.m

The error occurs at 
![image](https://github.com/georgeoneill/EBBcorr/assets/44780192/2d7601cd-e398-44bc-b3b8-80ca867cbbd0)

Could you give a clue how to fix it?

**Comment by georgeoneill** [comment]
Hello @razoralm, 

It appears the function `bf_features_tdcov.m` isn't in your distribution of SPM. Can you check in the DAiSS folder (find it in `[SPM]/toolbox/DAiSS`) and let me know if its there?

**Comment by razoralm** [comment]
Yes, definetely, it is not here -- where can I get it?
![image](https://github.com/georgeoneill/EBBcorr/assets/44780192/62bd21ab-b594-4717-bc67-fcce7a0852f0)

**Comment by georgeoneill** [comment]
The good news you can now get the up-to-the-minute version of SPM on [Github](https://github.com/spm/spm). I'll update the readme to reflect this too.

**Comment by razoralm** [comment]
Thank you! 
I will try the new version and will tell if it works

**Comment by razoralm** [comment]
It worked, thank you again!
